name: Continuous Integration
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.x'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm run test
      - name: Build
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: pnpm run build

      # Output build directory contents for debugging
      - name: List build output
        run: ls -la ./build || echo "build directory not found"
      - name: Deploy to netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true # Enable comments to easily find preview URL
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          enable-commit-status: true
          enable-github-deployment: true # Create GitHub deployment
          netlify-config-path: ./netlify.toml
          fails-without-credentials: true # Fail if credentials are missing or invalid

          alias: deploy-preview-${{ github.event.number }}- # Preview URL for pull requests
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
