# name: Continous Integration
# on: [push, pull_request]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           node-version: '22.x'
#       - run: npm run test
#       - run: npm run build

#   deploy:

